name: Build and Upload Artifacts

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk
      volumes:
        - /tmp:/home/github/x-tools

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations.
      # Consider changing this to true when your workflow is stable.
      fail-fast: false
      matrix:
        toolchain: [x86_64-linux, x86_64-mingw]

    steps:
    - uses: actions/checkout@v4

    - name: Setup crosstool-ng
      run: |
        apt install -y bison flex pkg-config texinfo help2man gawk libtool-bin libncurses5-dev && \
          git clone https://github.com/crosstool-ng/crosstool-ng
        cd crosstool-ng
        ./bootstrap && ./configure --enable-local && make -j

    - name: Build
      run: |
        cd ${{matrix.toolchain}}
        ../crosstool-ng/ct-ng build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: slowgames-toolchain-${{matrix.toolchain}}
        path: /tmp/x86_64-*/**/*
